<script lang="ts">
  import BackButton from "./BackButton.svelte";
  import {
    FillLayer,
    GeoJSON,
    LineLayer,
    hoverStateFilter,
    type LayerClickInfo,
  } from "svelte-maplibre";
  import { Link, layerId } from "./common";
  import { isLine } from "svelte-utils/map";
  import { SplitComponent } from "svelte-utils/top_bar_layout";
  import { app, mode, autosave } from "./stores";
  import { downloadGeneratedFile } from "svelte-utils";

  let gj = JSON.parse($app!.renderAutoBoundaries());

  function add(e: CustomEvent<LayerClickInfo>) {
    let name = window.prompt("What do you want to name the neighbourhood?");
    if (!name) {
      return;
    }
    try {
      // TODO Waypoints will be missing; editing will not work
      let feature = {
        type: "Feature",
        properties: {},
        // Trust generateId to make IDs in order
        geometry: gj.features[e.detail.features[0].id!].geometry,
      };
      $app!.setNeighbourhoodBoundary(name, feature);
      autosave();
      $app!.setCurrentNeighbourhood(name);
      $mode = {
        mode: "neighbourhood",
      };
    } catch (err) {
      console.log(err);
      window.alert(
        "Known georust bug hit, sorry. You may need to just refresh the page now.",
      );
    }
  }

  function download() {
    downloadGeneratedFile(
      "auto_boundaries.geojson",
      JSON.stringify(gj, null, "  "),
    );
  }
</script>

<SplitComponent>
  <div slot="top">
    <nav aria-label="breadcrumb">
      <ul>
        <li>
          <Link on:click={() => ($mode = { mode: "title" })}>
            Choose project
          </Link>
        </li>
        <li>
          <Link on:click={() => ($mode = { mode: "network" })}>
            Pick neighbourhood
          </Link>
        </li>
        <li>Use an auto-generated boundary</li>
      </ul>
    </nav>
  </div>

  <div slot="sidebar">
    <BackButton on:click={() => ($mode = { mode: "network" })} />
    <p>
      Click an area to use it as a neighbourhood. These are generated by finding
      roads, railways, and water thatform severances. There are many bugs; this
      is experimental.
    </p>
    <button class="secondary" on:click={download}>Export to GeoJSON</button>
  </div>

  <div slot="map">
    <GeoJSON data={gj} generateId>
      <FillLayer
        {...layerId("auto-boundaries-areas")}
        manageHoverState
        paint={{
          "fill-color": hoverStateFilter("cyan", "red"),
          "fill-opacity": 0.3,
        }}
        on:click={add}
        hoverCursor="pointer"
      />

      <LineLayer
        {...layerId("auto-boundaries-severances")}
        filter={isLine}
        manageHoverState
        paint={{
          "line-color": hoverStateFilter("black", "red"),
          "line-width": 3,
        }}
      />
    </GeoJSON>
  </div>
</SplitComponent>
