<script lang="ts">
  import { type ExpressionSpecification } from "maplibre-gl";
  import {
    FillLayer,
    GeoJSON,
    hoverStateFilter,
    LineLayer,
    type LayerClickInfo,
  } from "svelte-maplibre";
  import { downloadGeneratedFile } from "svelte-utils";
  import { isLine, isPolygon, makeRamp, Popup } from "svelte-utils/map";
  import { SplitComponent } from "svelte-utils/top_bar_layout";
  import BackButton from "./BackButton.svelte";
  import { layerId, Link } from "./common";
  import { areaLimits, simdColorScale, simdLimits } from "./common/colors";
  import { pickNeighbourhoodName } from "./common/pick_names";
  import PrioritizationSelect from "./prioritization/PrioritizationSelect.svelte";
  import { autosave, backend, editPerimeterRoads, mode } from "./stores";

  let gj = $backend!.getAutoBoundaries();
  let minArea = 0;
  let removeNonRoad = true;
  let selectedPrioritization: "none" | "area" | "simd" = "none";

  function add(e: CustomEvent<LayerClickInfo>) {
    let name = pickNeighbourhoodName(
      $backend!,
      "What do you want to name the neighbourhood?",
      "",
    );
    if (!name) {
      return;
    }
    try {
      let feature = {
        type: "Feature" as const,
        // Omit waypoints and lazily fill them out.
        properties: {},
        // Trust generateId to make IDs in order
        geometry: gj.features[e.detail.features[0].id as number].geometry,
      };
      $backend!.setNeighbourhoodBoundary(name, feature);
      autosave();
      $backend!.setCurrentNeighbourhood(name, $editPerimeterRoads);
      $mode = {
        mode: "neighbourhood",
      };
    } catch (err) {
      console.log("error when setting auto-generated neighborhood", err);
      window.alert(
        "Sorry, an error occurred. You may need to refresh the page for the application to continue working.",
      );
    }
  }

  function download() {
    downloadGeneratedFile(
      "auto_boundaries.geojson",
      JSON.stringify(gj, null, "  "),
    );
  }

  function makeFilter(
    minArea: number,
    removeNonRoad: boolean,
  ): ExpressionSpecification {
    let x: ExpressionSpecification = [
      "all",
      isPolygon,
      [">=", ["get", "area_km2"], minArea],
    ];
    if (removeNonRoad) {
      x.push(["get", "touches_big_road"]);
    }
    return x;
  }
</script>

<SplitComponent>
  <div slot="top">
    <nav aria-label="breadcrumb">
      <ul>
        <li>
          <Link on:click={() => ($mode = { mode: "title", firstLoad: false })}>
            Choose project
          </Link>
        </li>
        <li>
          <Link on:click={() => ($mode = { mode: "pick-neighbourhood" })}>
            Pick neighbourhood
          </Link>
        </li>
        <li>Use an auto-generated boundary</li>
      </ul>
    </nav>
  </div>

  <div slot="sidebar">
    <BackButton on:click={() => ($mode = { mode: "pick-neighbourhood" })} />

    <p>
      Click an area to use it as a neighbourhood. These are generated by finding
      roads, railways, and water that form severances. There are many bugs; this
      is experimental. The colors are arbitrary, just to distinguish better.
    </p>

    <h3>Prioritization</h3>
    <p>Compare metrics across candidate neighbourhoods.</p>
    <PrioritizationSelect bind:selectedPrioritization />

    <button class="secondary" on:click={download}>Export to GeoJSON</button>

    <label>
      Minimum area (km²)
      <input type="number" bind:value={minArea} min="0" max="1" step="0.01" />
    </label>

    <label>
      <input type="checkbox" bind:checked={removeNonRoad} />
      Remove areas not touching a big road
    </label>
  </div>

  <div slot="map">
    <GeoJSON data={gj} generateId>
      <LineLayer
        {...layerId("auto-boundaries-severances")}
        filter={isLine}
        manageHoverState
        paint={{
          "line-color": hoverStateFilter("black", "red"),
          "line-width": 3,
        }}
      />

      <FillLayer
        {...layerId("neighbourhood-boundaries", false)}
        filter={makeFilter(minArea, removeNonRoad)}
        paint={{
          "fill-color": [
            "match",
            ["%", ["id"], 5],
            0,
            "blue",
            1,
            "yellow",
            2,
            "green",
            3,
            "purple",
            4,
            "orange",
            "black",
          ],
          "fill-opacity": hoverStateFilter(0.2, 0.4),
        }}
        layout={{
          visibility: selectedPrioritization == "none" ? "visible" : "none",
        }}
        manageHoverState
        hoverCursor="pointer"
        on:click={add}
      >
        <!-- 
             REVIEW: How to do type checking to the usage of `props`? 
             Maybe something like this: https://stackoverflow.com/questions/73531618/svelte-components-with-generics
           -->
        <Popup openOn="hover" let:props>
          <b>Area:</b>
          {props.area_km2.toFixed(1)} km²
          <br />
          <b>SIMD (percentile):</b>
          {props.simd.toFixed(1)}
        </Popup>
      </FillLayer>

      <!-- REVIEW: Should clicking on a neighbourhood in the "prioritization" layer take you to neighbourhood? -->
      <FillLayer
        {...layerId("neighbourhood-prioritization-simd")}
        filter={makeFilter(minArea, removeNonRoad)}
        paint={{
          "fill-color": makeRamp(["get", "simd"], simdLimits, simdColorScale),
          "fill-opacity": hoverStateFilter(0.7, 0.9),
        }}
        layout={{
          visibility: selectedPrioritization == "simd" ? "visible" : "none",
        }}
        manageHoverState
        hoverCursor="pointer"
        on:click={add}
      >
        <Popup openOn="hover" let:props>
          <b>SIMD:</b>
          {props.simd.toFixed(1)}
        </Popup>
      </FillLayer>
      <FillLayer
        {...layerId("neighbourhood-prioritization-area")}
        filter={makeFilter(minArea, removeNonRoad)}
        paint={{
          "fill-color": makeRamp(
            ["get", "area_km2"],
            areaLimits,
            simdColorScale,
          ),
          "fill-opacity": hoverStateFilter(0.7, 0.9),
        }}
        layout={{
          visibility: selectedPrioritization == "area" ? "visible" : "none",
        }}
        manageHoverState
        hoverCursor="pointer"
        on:click={add}
      >
        <Popup openOn="hover" let:props>
          <b>Area:</b>
          {props.area_km2.toFixed(1)} km²
        </Popup>
      </FillLayer>
    </GeoJSON>
  </div>
</SplitComponent>
